[package]
name = "monkey"
version = "0.1.0"
authors = ["Numan Elahi <elahinouman.elahi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
users = "0.9.1"